[package]
name = "rust-playground"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.5"

[target.'cfg(shuttle)'.dependencies]
shuttle = "0.6.0"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
